### ISSUE TITLE
Plugin Can't load

### ISSUE THREAD

**Issue by rh-programm** [marcelo-mason/SimpleClans#455]
`[16:22:05] [Server thread/ERROR]: Could not load 'plugins/SimpleClans.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_131]
	at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_131]
	at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_131]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_131]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	... 5 more`

**Comment by RoinujNosde** [comment]
Are you using the latest version? http://104.236.246.108:8080/job/SimpleClans/

**Comment by rh-programm** [comment]
Yes, I use the latest version

**Comment by RoinujNosde** [comment]
Could you please test if it happens on Spigot 1.12?
I'm at work right now.

**Comment by rh-programm** [comment]
I use a Spigot 1.8.9 server ...

**Comment by RoinujNosde** [comment]
I saw that in the log. This is why I asked you to test...

**Comment by rh-programm** [comment]
On my test server (local) it goes on the 1.12 as well as on the 1.8

**Comment by RoinujNosde** [comment]
https://pastebin.com/t4vJsDYk
Loads normally here.
May you send me your jar?

**Comment by rh-programm** [comment]
OK, I have now the whole server file downloaded and given on my LocalHost server - there everything works ...

**Comment by RoinujNosde** [comment]
So... This is not an issue?

**Comment by rh-programm** [comment]
Apparently not anymore ...
