### ISSUE TITLE
DynMap Addon Can't load

### ISSUE THREAD

**Issue by rh-programm** [marcelo-mason/SimpleClans#456]
`[16:30:24] [Server thread/ERROR]: Could not load 'plugins/Dynmap-SimpleClans.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_131]
	at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_131]
	at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_131]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_131]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	... 5 more`

**Comment by RoinujNosde** [comment]
@marcelo-mason
Is this add-on still maintained?

**Comment by rh-programm** [comment]
On the plugins page (https://dev.bukkit.org/projects/simpleclans) there is a link to this addon ... and this I use (https://dev.bukkit.org/projects/dynmap-simpleclans)

**Comment by RoinujNosde** [comment]
I know, but there is nothing I can do, I don't have its source code.

**Comment by rh-programm** [comment]
ok

**Comment by RoinujNosde** [comment]
Wait for Marcelo's answer, dude :D

**Comment by rh-programm** [comment]
OK, I have now the whole server file downloaded and given on my LocalHost server - there everything works ...
