### ISSUE TITLE
Reqest: verifying you want to leave a clan.

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#493]
Via a player of mine, they were using the clan chat with “/c leave it to me” to send a message to crew chat.
I also have seen a player trying to teach another player how to leave a crew by meaning to type  ./crew leave in chat but he missed the dot.

Can we get some verification someone wishes to leave a group before doing it on a single command? 

Thank you.

**Comment by RoinujNosde** [comment]
[SimpleClans.zip](https://github.com/marcelo-mason/SimpleClans/files/3437589/SimpleClans.zip)

@FrozenBeard could you test it?

**Comment by FrozenBeard** [comment]
@RoinujNosde Thanks, Its on the server and I have asked my users to test :)

**Comment by RoinujNosde** [comment]
Thanks, I added 3 new messages. So you must update your old language file if you're using it.

**Comment by FrozenBeard** [comment]
Nope, stopped /crew leave working all together (mines chnaged to crew over clan)

**Comment by RoinujNosde** [comment]
Any errors or messages?

**Comment by FrozenBeard** [comment]
No it doesn't say anything, stops messages being sent in chat until you relog.

**Comment by RoinujNosde** [comment]
Did you add manually the 3 new messages?

**Comment by FrozenBeard** [comment]
Ah nuts no, I must have skimmed your message, I'll do that.

**Comment by RoinujNosde** [comment]
> I'll do that.
Let me know if it works.

> maybe add a timer if they don't reply to cancel it?
How many seconds?

**Comment by FrozenBeard** [comment]
I added the new language.yml lines, there was a full reboot and it wiped the language.yml back to what it was: this is my edited version: https://gist.github.com/FrozenBeard/2d159e75b9046ec87509ba7784233584
This is what it reverts it to:
https://gist.github.com/FrozenBeard/4b4f7e5a6f9113da009016a31fd622d4

I also tried copying it over and did a /crew reload which reloads the plugin, but not the languages file.

When I type in chat I get this error:
`[11:56:03] [Server thread/WARN]: [SimpleClans] Plugin SimpleClans v2.7.15 generated an exception whilst handling conversation input
java.lang.NullPointerException: null
	at java.text.MessageFormat.applyPattern(MessageFormat.java:436) ~[?:1.8.0_201]
	at java.text.MessageFormat.<init>(MessageFormat.java:362) ~[?:1.8.0_201]
	at java.text.MessageFormat.format(MessageFormat.java:840) ~[?:1.8.0_201]
	at net.sacredlabyrinth.phaed.simpleclans.conversation.ResignPrompt.getPromptText(ResignPrompt.java:59) ~[?:?]
	at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:284) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:60) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1325) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1311) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:861) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]`

Maybe because its not able to load the changes to the language.yml?

**Comment by FrozenBeard** [comment]
Ahoy!
Ok sorry its been hectic for my IRL recently, I got my language file updated so I can see this working, can you please not make the yes/no case sensitive? And have a error return if they write anything apart from yes/no? Could you do it so if they write anything apart from Yes/yes/y that it just ends up as "no", thats probability the most simplest design choice here, then if they miss the message in chat and start talking then it'll auto be "no".

**Comment by RoinujNosde** [comment]
Will do
