### ISSUE TITLE
Console spam error after update latest spigot build

### ISSUE THREAD

**Issue by comonier** [marcelo-mason/SimpleClans#509]
https://paste.ofcode.org/tHjmx5bKjfuEX6hD4EtQwE
https://paste.ofcode.org/CH3TjSbPxkAkqgpsALCgDj
ess version:
[Sat, 25. May 2019 21:19:22 EDT INFO] CONSOLE issued server command: /ess version
[Sat, 25. May 2019 21:19:22 EDT INFO] Server version: 1.14.1-R0.1-SNAPSHOT git-Spigot-03bd4b0-17da342 (MC: 1.14.1)
[Sat, 25. May 2019 21:19:22 EDT INFO] EssentialsX version: 2.16.1.180-mc114-b95
[Sat, 25. May 2019 21:19:22 EDT INFO] PermissionsEx version: 1.23.4
[Sat, 25. May 2019 21:19:22 EDT INFO] Vault version: 1.7.2-b107
[Sat, 25. May 2019 21:19:22 EDT INFO] EssentialsXChat version: 2.16.1.180-mc114-b95
[Sat, 25. May 2019 21:19:22 EDT INFO] EssentialsXGeoIP version: 2.16.1.180-mc114-b95
[Sat, 25. May 2019 21:19:22 EDT INFO] EssentialsXSpawn version: 2.16.1.180-mc114-b95

**Comment by comonier** [comment]
sorry mistake wrong plugin site =P

**Comment by comonier** [comment]
31.05 19:11:12 [Server] Async Chat Thread - #38/ERROR Could not pass event AsyncPlayerChatEvent to SimpleClans v2.7.11
31.05 19:11:12 [Server] INFO org.bukkit.event.EventException: null
31.05 19:11:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
31.05 19:11:12 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
31.05 19:11:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
31.05 19:11:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
31.05 19:11:12 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1592) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
31.05 19:11:12 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1530) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
31.05 19:11:12 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
31.05 19:11:12 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
31.05 19:11:12 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
31.05 19:11:12 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
31.05 19:11:12 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
31.05 19:11:12 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
31.05 19:11:12 [Server] INFO Caused by: java.lang.IllegalStateException: ChatEvent cannot be triggered asynchronously from another thread.
31.05 19:11:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
31.05 19:11:12 [Server] INFO at net.sacredlabyrinth.phaed.simpleclans.managers.ClanManager.processClanChat(ClanManager.java:1151) ~[?:?]
31.05 19:11:12 [Server] INFO at net.sacredlabyrinth.phaed.simpleclans.listeners.SCPlayerListener.onPlayerChat(SCPlayerListener.java:151) ~[?:?]
31.05 19:11:12 [Server] INFO at sun.reflect.GeneratedMethodAccessor421.invoke(Unknown Source) ~[?:?]
31.05 19:11:12 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
31.05 19:11:12 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
31.05 19:11:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
31.05 19:11:12 [Server] INFO ... 11 more
