### ISSUE TITLE
Error occurred while enabling SimpleClans v2.7.19 java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#535]
I decided to test the latest update locally before I do it on production this time, and lucky caught a NullPointerException before pushing live, this was run on an old database I had on my local server, but after I backdated to v2.7.18 it did boot.

```
[13:06:31] [Server thread/INFO]: [SimpleClans] Enabling SimpleClans v2.7.19
[13:06:31] [Server thread/INFO]: [SimpleClans] MySQL Connection successful
[13:06:32] [Server thread/INFO]: [SimpleClans] Crews: 266
[13:06:32] [Server thread/INFO]: [SimpleClans] purging players data: {0}
[13:06:32] [Server thread/ERROR]: Error occurred while enabling SimpleClans v2.7.19 (Is it up to date?)
java.lang.NullPointerException: null
	at net.sacredlabyrinth.phaed.simpleclans.Clan.addBb(Clan.java:419) ~[?:?]
	at net.sacredlabyrinth.phaed.simpleclans.managers.StorageManager.deleteClanPlayer(StorageManager.java:715) ~[?:?]
	at net.sacredlabyrinth.phaed.simpleclans.managers.StorageManager.purgeClanPlayers(StorageManager.java:241) ~[?:?]
	at net.sacredlabyrinth.phaed.simpleclans.managers.StorageManager.importFromDatabase(StorageManager.java:169) ~[?:?]
	at net.sacredlabyrinth.phaed.simpleclans.managers.StorageManager.<init>(StorageManager.java:38) ~[?:?]
	at net.sacredlabyrinth.phaed.simpleclans.SimpleClans.onEnable(SimpleClans.java:78) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[13:06:32] [Server thread/INFO]: [SimpleClans] Disabling SimpleClans v2.7.19
[13:06:32] [Server thread/ERROR]: Error occurred while disabling SimpleClans v2.7.19 (Is it up to date?)
java.lang.NullPointerException: null
	at net.sacredlabyrinth.phaed.simpleclans.SimpleClans.onDisable(SimpleClans.java:119) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

**Comment by RoinujNosde** [comment]
I think I found the cause.

**Comment by RoinujNosde** [comment]
https://github.com/marcelo-mason/SimpleClans/releases/tag/v2.7.20

Please test it with your old database.
