### ISSUE TITLE
/clan vitals not working

### ISSUE THREAD

**Issue by JH3Y50N** [marcelo-mason/SimpleClans#577]
/clan saude: http://prntscr.com/s1zy0h
ERROR:
`
[18:45:40 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'clan' in plugin SimpleClans v2.9.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchFieldError: GOLDEN_SWORD
        at net.sacredlabyrinth.phaed.simpleclans.managers.ClanManager.getWeaponString(ClanManager.java:621) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.commands.VitalsCommand.addRows(VitalsCommand.java:98) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.commands.VitalsCommand.execute(VitalsCommand.java:71) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.executors.ClanCommandExecutor.onCommand(ClanCommandExecutor.java:155) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        ... 15 more`

/clan banco withdraw: http://prntscr.com/s1zzvb
ERRO: Consigo depositar dinheiro mas não consigo sacar o mesmo

ATT o withdraw descobri como resolver, /clan toggle withdraw o withdraw deveria ser ativo por padrão no plugin.

/clan reload: http://prntscr.com/s20232
ERRO: Perco meu cargo no clã quando dou reload, sendo que sou o dono do clã

**Comment by JH3Y50N** [comment]
o último erro ali acontece as vezes, nem sempre acontece, agora o /clan saude está bugado já faz algumas versões...

**Comment by RoinujNosde** [comment]
> ERRO: Perco meu cargo no clã quando dou reload, sendo que sou o dono do clã

Não consigo reproduzir esse problema.

> agora o /clan saude está bugado já faz algumas versões...

Você está usando uma versão antiga do Paper. Já considerou atualizar? Tem um plugin que deixa o combate a moda antiga: https://www.spigotmc.org/resources/oldcombatmechanics-disable-1-9-hit-cooldown.19510/
E tem um plugin que permite que várias versões entrem: https://www.spigotmc.org/resources/viaversion.19254/

**Comment by JH3Y50N** [comment]
não irei atualizar, continuarei usando a 1.8, já uso viaversion para permitir jogadores acima da 1.8, me explique qual o problema do /clan saude, sobre o bug das versões eu digo a versão do SimpleClans estava bugada, não é a versão do servidor, faz alguns versões do SimpleClans, acima da 1.8.3 se não me engano esse bug começou a acontecer.

**Comment by RoinujNosde** [comment]
> me explique qual o problema do /clan saude

Esse comando pega as armaduras do jogador, comida no inventário, etc e mostra esses dados
Só que o Material de uma boa parte dos itens e blocos mudou nas novas versões do Mine. O plugin tá programado para as novas versões e não encontra os Materials corretos na sua versão.
