### ISSUE TITLE
Could not pass event PlayerCommandPreprocessEvent to SimpleClans v2.12.1

### ISSUE THREAD

**Issue by SrBedrock** [marcelo-mason/SimpleClans#626]
SimpleClans v2.12.1
[Chatty v2.18.1](https://github.com/Brikster/Chatty)

```
[06:20:30 INFO]: JulioBruxo issued server command: /global
[06:20:30 ERROR]: Could not pass event PlayerCommandPreprocessEvent to SimpleClans v2.12.1
java.lang.NullPointerException: null
at net.sacredlabyrinth.phaed.simpleclans.listeners.SCPlayerListener.onPlayerCommandPreprocess(SCPlayerListener.java:115) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor123.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1865) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1681) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1162) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1155) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1131) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at java.lang.Thread.run(Thread.java:832) [?:?]
[06:20:31 INFO]: ThiagoROX issued server command: /g
[06:20:31 INFO]: genbuz issued server command: /claim
[06:20:31 INFO]: [Ultimate] [BRX] JulioBruxo» a
[06:20:35 INFO]: [Membro] [BRX] GOG999» global
[06:20:39 INFO]: [Admin] ThiagoROX» Flawkes mandar mensagem no global estando no chat local..
[06:20:44 INFO]: ThiagoROX issued server command: /g
[06:20:47 INFO]: GOG999 issued server command: /global aa
[06:20:47 ERROR]: Could not pass event PlayerCommandPreprocessEvent to SimpleClans v2.12.1
java.lang.NullPointerException: null
at net.sacredlabyrinth.phaed.simpleclans.listeners.SCPlayerListener.onPlayerCommandPreprocess(SCPlayerListener.java:115) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor123.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1865) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1681) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1162) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1155) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1131) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by RoinujNosde** [comment]
Me envie a sua config.

**Comment by SrBedrock** [comment]
```
[17:55:32 INFO]: BRABOX66 issued server command: /global FASSO FARM DE CACTO POR 30K
[17:55:32 ERROR]: Could not pass event PlayerCommandPreprocessEvent to SimpleClans v2.12.1
java.lang.NullPointerException: null
```

**Comment by SrBedrock** [comment]
> Me envie a sua config.

Já achei o erro, simpleclans também tem um comando `/global`

**Comment by SrBedrock** [comment]
Após alterar o comando o erro parou de acontecer.`
```
[18:04:02 INFO]: ThiagoROX issued server command: /global
[18:04:02 INFO]: [Membro] [FIM] Gibby» alguem x1?
[18:04:02 INFO]: [ShopGUIPlus] diego2 comprou 1 x Sheep Spawn Egg por 15,000$ no shop ovos
[18:04:03 INFO]: Quantiminck issued server command: /a rsrs
[18:04:03 INFO]: [SimpleClans] [a] [TKA] Quantiminck» rsrs
[18:04:04 INFO]: Teixeira_ issued server command: /r Pode chamar, o Clax falou que tretou c ele
[18:04:07 INFO]: zezinho27032006 issued server command: /mcstats
[18:04:08 INFO]: [l] [Membro] Marinato» gg dps te dou o money
[18:04:08 INFO]: Sr_cosmico issued server command: /home
[18:04:09 INFO]: Frostgameh5 issued server command: /go FarmDeXP
[18:04:09 INFO]: ThiagoROX issued server command: /global aaaa
[18:04:10 INFO]: WaterPotion issued server command: /tpa ChovendoFrang
```
