### ISSUE TITLE
[Server thread/ERROR]: null

### ISSUE THREAD

**Issue by megamineservidores** [marcelo-mason/SimpleClans#633]
[16:58:09] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'deny' in plugin SimpleClans v2.12.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_252]
	at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_252]
	at net.sacredlabyrinth.phaed.simpleclans.managers.RequestManager.processCreateAlly(RequestManager.java:388) ~[?:?]
	at net.sacredlabyrinth.phaed.simpleclans.managers.RequestManager.processResults(RequestManager.java:297) ~[?:?]
	at net.sacredlabyrinth.phaed.simpleclans.managers.RequestManager.deny(RequestManager.java:235) ~[?:?]
	at net.sacredlabyrinth.phaed.simpleclans.executors.DenyCommandExecutor.onCommand(DenyCommandExecutor.java:47) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 15 more

**Comment by RoinujNosde** [comment]
Qual é o passo a passo para o erro ocorrer?

**Comment by megamineservidores** [comment]
Fui ver nos logs e tava lá esse erro

**Comment by JH3Y50N** [comment]
> Fui ver nos logs e tava lá esse erro

envia o log completo, onde mostra os comandos sendo usados para saber oque está ocorrendo
